cba/terraform-solution-implementation/08-vmc-deploy-cloud-proxy/main.tf, cba/terraform-solution-implementation/08-vmc-deploy-cloud-proxy/terraform.tfvars.example, cba/terraform-solution-implementation/08-vmc-deploy-cloud-proxy/variables.tf, cba/terraform-solution-implementation/08-vmc-deploy-cloud-proxy/versions.tf, cba/terraform-solution-implementation/09-vmc-deploy-cloud-extensibility-proxy/main.tf, cba/terraform-solution-implementation/09-vmc-deploy-cloud-extensibility-proxy/terraform.tfvars.example, cba/terraform-solution-implementation/09-vmc-deploy-cloud-extensibility-proxy/variables.tf, cba/terraform-solution-implementation/09-vmc-deploy-cloud-extensibility-proxy/versions.tf
- Added automatic collection of the One Time Key (OTK) from VMC
- Added the use of terracurl for REST API Calls
Signed-off-by: Gary Blake <gblake@vmware.com>
=> feat: Add enhancements to Cloud Proxy deployments

cba/terraform-solution-implementation/07-nsx-permissions-apply/main.tf, cba/terraform-solution-implementation/07-nsx-permissions-apply/outputs.tf, cba/terraform-solution-implementation/07-nsx-permissions-apply/terraform.tfvars.example, cba/terraform-solution-implementation/07-nsx-permissions-apply/variables.tf, cba/terraform-solution-implementation/07-nsx-permissions-apply/versions.tf
- Implemented using terracurl provider
Signed-off-by: Gary Blake <gblake@vmware.com>
=> Enhancement to NSX Permissions Apply

cba/terraform-sample-project/13-cloud-assembly-content-sharing/variables.tf, cba/terraform-solution-implementation/15-vmc-cloud-zone-config/main.tf, cba/terraform-solution-implementation/15-vmc-cloud-zone-config/terraform.tfvars.example, cba/terraform-solution-implementation/15-vmc-cloud-zone-config/variables.tf
- Fixed `default` syntax in variable for Content Sharing
- Fixed tags for Cloud Zone Config
Signed-off-by: Gary Blake <gblake@vmware.com>
=> fix: walk-thru testing

pca/README.md
Update dependencies.
Signed-off-by: Ryan Johnson <johnsonryan@vmware.com>
Issue Number: GH-XXXX
=> docs(pca): update `README.md`

.github/CODEOWNERS, CODEOWNERS
Update `CODEOWNERS`
Signed-off-by: Ryan Johnson <johnsonryan@vmware.com>
Issue Number: GH-XXXX
=> chore(gh): update `CODEOWNERS`

CODE_OF_CONDUCT.md
- Formatting of CODE_OF_CONDUCT.md
Signed-off-by: Gary Blake <gblake@vmware.com>
=> chore: formatting of code of conduct

README.md
- Updated README.md with Health Reporting and Monitoring
=> chore: update main repo readme

hrm/README.md
Updated readme to help guide the user with Python installation along with the dependency modules.
Resolves #27
=> docs: add guidance for installing python

hrm/env.json
- Updated default env.json to place logs in a loga folder rather than test_results
=> feat: improve default logs folder

hrm/README.md, hrm/env.json, hrm/examples/run_send-data-to-vrops.bat, hrm/examples/run_sos-data-push-vrops.bat, hrm/send-data-to-vrops.py, hrm/utils/FolderUtility.py, hrm/utils/LogUtility.py
Fixes issues 29, 30 i.e.
- Adjust certificate thresholds
- Update formatting of date column in backup dashboard
Update to README.md
Update log location and name
Closes #29
Closes #30
=> Fix for 29, 30, readme and update log file location and name

hrm/README.md
Updated the version of `VMware.CloudFoundation.Reporting` PowerShell module in `hrm/README.md`.
Issue Number: n/a
=> docs: update `hrm/README.md`

.idea/workspace.xml, alb/ansible-examples/certificate-renewal-playbook/README.md, alb/ansible-examples/certificate-renewal-playbook/variables.yml, alb/ansible-examples/cluster-deployment-playbook/README.md, alb/ansible-examples/cluster-deployment-playbook/tasks/deploy_controllers.yaml, alb/ansible-examples/cluster-deployment-playbook/variables.yml, alb/ansible-examples/cluster-upgrade-playbook/README.md, alb/ansible-examples/cluster-upgrade-playbook/variables.yml, alb/ansible-examples/node-replacement-playbook/README.md, alb/ansible-examples/node-replacement-playbook/node_replacement.yaml, alb/ansible-examples/node-replacement-playbook/tasks/deploy_new_controller.yaml, alb/ansible-examples/node-replacement-playbook/variables.yml, alb/ansible-examples/nsxt-cloud-data-segment-playbook/README.md, alb/ansible-examples/nsxt-cloud-data-segment-playbook/variables.yml, alb/ansible-examples/nsxt-cloud-deployment-playbook/README.md, alb/ansible-examples/nsxt-cloud-deployment-playbook/variables.yml, alb/ansible-examples/password-change-playbook/README.md, alb/ansible-examples/password-change-playbook/variables.yml, alb/ansible-examples/remote-authentication-playbook/README.md, alb/ansible-examples/remote-authentication-playbook/remote_auth.yaml, alb/ansible-examples/remote-authentication-playbook/variables.yml
- [ X] I have read and agree to the project's Code of Conduct.
- [ X] This is an enhancement or feature.
- [X ] This is a documentation update.
Issue Number: GH-XXXX
- [ X] Tests have been completed (for bug fixes / features).
- [ X] Documentation has been added / updated (for bug fixes / features).
- [X ] No, there are no breaking …
=> NSX ALB - Update VVS Ansible Playbooks for 22.x

hrm/CHANGELOG.md, hrm/setup.cfg, hrm/source/main/send-data-to-vrops.py
- Updated code to handle special characters in passwords for PowerShell cmdlets
Closes #59 
Script log after making the change - 
```
[2023-07-18 18:21:43] INFO - [PSUtility.py:45] - Publish-StorageCapacityHealth -                                                                                                          server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass ******** -allDomains -outputJson /opt/vmware/hrm/logs/send-data_2023-07-18_18-21-16 -localUser vcf -localPass ********
[2023-07-18 18:22:46] INFO - [PSUtility.py:45] - output received = JSON Created at /opt/vmware/hrm/logs/send-data_2023-07-18_18-21-16/07-18-2023_06_22_46-storagecapacityhealth-status.json
```
=> fix: special character handling for passwords used by PowerShell cmdlets

hrm/CHANGELOG.md
Update release date in changelog.md
=> chore: release prep - update release date

hrm/README.md
=> chore: add badges to `README.md`

alb/ansible-examples/remote-authentication-playbook/variables.yml
=> Fixing values in variables.yml in ALB ansible remote authentication playbook

README.md, hrm/README.md, hrm/setup.cfg, hrm/source/main/encrypt-passwords.py, hrm/source/main/notifications.py, hrm/source/main/send-data-to-vrops.py
=> aria rebranding updates

CHANGELOG.md, LICENSE, NOTICE, README.md, appliance/README.md, appliance/appliance-build.sh, appliance/appliance-unregister.ps1, appliance/files/rc.local, appliance/files/setup-01-os.sh, appliance/files/setup-02-network.sh, appliance/files/setup-099-banner.sh, appliance/files/setup.sh, appliance/manual/add_ovf_properties.sh, appliance/override.pkrvars.hcl, appliance/photon.auto.pkrvars.hcl, appliance/photon.pkr.hcl, appliance/scripts/photon-cleanup.sh, appliance/scripts/photon-settings.sh, appliance/variables.pkr.hcl, cba/cbaTerraformMenu.ps1, hrm/README.md
Update copyright from VMware, Inc. to Broadcom.
=> chore: update copyright

hrm/LICENSE, hrm/NOTICE, hrm/README.md, hrm/setup.cfg, hrm/source/main/encrypt-passwords.py, hrm/source/main/notifications.py, hrm/source/main/send-data-to-vrops.py, hrm/source/main/utils/FolderUtility.py, hrm/source/main/utils/LogUtility.py, hrm/source/main/utils/PSUtility.py, hrm/source/main/utils/SosRest.py
- Update copyright from VMware, Inc. to Broadcom.
- Add LICENSE and NOTICE to `/hrm`.
- Add SPDX headers.
=> chore: update copyright and add headers

hrm/CHANGELOG.md, hrm/README.md, hrm/setup.cfg, hrm/source/main/env.json, hrm/source/main/send-data-to-vrops.py, hrm/source/main/utils/SosRest.py
Enhanced the VMware Aria Operations Dashboards in HRM to have parity with VMware.CloudFoundation.Reporting.
Added: 
1. HRM ESXi Connection Health
2. HRM SDDC Free Pool
3. HRM VM Connected CDROM
4. SOS Version Health
Closes  #39
=> feat(hrm): add additional dashboards

hrm/README.md
=> chore: fix link in `README.md`

appliance/README.md, appliance/appliance-build.sh, appliance/appliance-unregister.ps1, appliance/files/rc.local, appliance/files/setup-01-os.sh, appliance/files/setup-02-network.sh, appliance/files/setup-099-banner.sh, appliance/files/setup.sh, appliance/manual/add_ovf_properties.sh, appliance/override.pkrvars.hcl, appliance/photon.auto.pkrvars.hcl, appliance/photon.pkr.hcl, appliance/scripts/photon-cleanup.sh, appliance/scripts/photon-settings.sh, appliance/variables.pkr.hcl
- Bumps Packer to v1.10.1.
- Bumps Packer Plugin for VMware to v1.0.11.
- Updates copyright years.
=> chore(deps): bump packer and packer-plugin-vmware

README.md, hrm/CHANGELOG.md, hrm/LICENSE, hrm/NOTICE, hrm/README.md, hrm/setup.cfg
- Markdown corrections.
- Copywrite updates.
=> chore: update hrm

cmm/README.md, cmm/artifacts/Alert Definitions.xml, cmm/artifacts/Dashboards.json, cmm/artifacts/Supermetrics.json, hrm/README.md
Proof of Concept: Adds dashboards for Private Cloud Maturity Model.
=> feat: add cmm dashboards

hrm/source/main/send-data-to-vrops.py, hrm/source/main/utils/SosRest.py
Add function `get_list_of_workload_domain` to retrieve a list of workload domains from SDDC Manager. Modify script to loop through pulling sos_health check and upload to VCF Operations per workload domain.
=> feat(hrm): add `get_list_of_workload_domain`
